export { AgentRef } from './client.js'
export {
  AgentRefError,
  AuthError,
  ConflictError,
  ForbiddenError,
  NotFoundError,
  RateLimitError,
  ServerError,
  ValidationError,
} from './errors.js'
export type {
  AgentRefConfig,
  Affiliate,
  AffiliateStatus,
  BillingStatus,
  BillingTier,
  BillingTierId,
  CommissionType,
  Conversion,
  ConversionStats,
  ConversionStatus,
  Coupon,
  CreateCouponParams,
  CreateProgramParams,
  Flag,
  FlagStats,
  FlagStatus,
  FlagType,
  Invite,
  Merchant,
  MutationOptions,
  PaginatedResponse,
  PaginationMeta,
  PendingAffiliate,
  Payout,
  PayoutStats,
  PayoutStatus,
  Program,
  ProgramStats,
  ProgramStatus,
  ResolveFlagParams,
  UpdateProgramParams,
} from './types/index.js'
